# Generated by Django 2.0 on 2018-12-11 07:53

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181211_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
    ]
